# Generated by Django 3.2.5 on 2021-07-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='this is test', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(default='5 Month', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azureapp.project')),
            ],
        ),
    ]
