# Generated by Django 3.2.5 on 2021-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureapp', '0002_auto_20210706_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
